trigger:
  branches:
    include:
      - "main"

pool:
  name: "planet-express-docker-agents"

variables:
- name: usecache
  value: false

steps:
- script: ./build.sh $(Build.SourceBranchName) $(Build.SourceVersion) $(usecache) 
  workingDirectory: .
  name: buildThinClient
  displayName: 'Build Squashfs'
- task: Docker@2
  inputs:
    containerRegistry: 'DG Modules Container Registry'
    repository: 'planetexpress/thinclient-base:21.04'
    command: 'push'
    Dockerfile: '.'
    buildContext: '.'
    tags: 'latest'

